project:
  type: website

website:
  title: "Docker R MLOps"
  page-navigation: true
  open-graph: true
  twitter-card: true
  cookie-consent: false
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - 1_linear_regression/doc.qmd
          - 2_linear_regression_mlflow/doc.qmd
      - section: "Tidymodels"
        contents:
          - 3_tidy_linear_regression/doc.qmd

  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
      
theme:
  light: flatly
  dark: darkly
  
format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

